#pragma config(StandardModel, "POE + CIM Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
/*
Move the servo to position 127 until a dark object is detected
Move servo to position -127
*/
setServo(servoMotor, 127);
waitUntil(SensorValue[in3] >= 500);
setServo(servoMotor, -127);

}
