#pragma config(StandardModel, "POE + CIM Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int closestDistance;

task trackSonar() {
	closestDistance = 300;
	while(1==1) {
		if (SensorValue[dgtl5] < closestDistance) {
			closestDistance = SensorValue[dgtl5];
		}
		if (SensorValue[dgtl1] == 1) {
			closestDistance = 300;
		}
	}
}
task main()
{

/*
. Create a program that will run a motor back and forth 20 times, 0.5 seconds each way
Test the program and troubleshoot until the expected behavior has occurred
Make sure your code is documented with a task description, pseudocode, and line-by-line comments
Save the program
You will reuse this program in Activity 3.1.6.
*/
startTask(trackSonar);
int multiplier = 1;
	for (int i = 0; i < 20 * 2; i++) {
		startMotor(leftMotor, 127 * multiplier);
		wait(.5);
		multiplier *= -1;
	}
}
