#pragma config(Sensor, in2,    pot,            sensorPotentiometer)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
/*
Verify that the potentiometer is at a value of less than 2048
Turn on the greenLED until the potentiometer is at a value greater than 2048
Turn off the greenLED
Turn on the leftMotor at half power until the potentiometer is at a value of less than 2048
Turn leftMotor off
*/

waitUntil(SensorValue[in2] < 2048);
startMotor(rightMotor, 63.5);
waitUntil(SensorValue[in2] > 2048);
stopMotor(rightMotor);
startMotor(leftMotor, 63.5);
waitUntil(SensorValue[in2] < 2048);
stopMotor(leftMotor);

}
