#pragma config(StandardModel, "POE + CIM Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
/*
D.  Make one motor spin whenever a button is pressed and a second motor spin whenever a limit switch is pressed
This behavior repeats indefinitely, as the two actions are independent
*/

	while (1 == 1) {
		if (SensorValue[dgtl2] == 1) {
			startMotor(leftMotor, 127);
		} else {
			stopMotor(leftMotor);
		}
		if (SensorValue[dgtl1] == 1) {
			startMotor(rightMotor, 127);
		} else {
			stopMotor(rightMotor);
		}
	}

	// For loops work
	/*
	for(int i = 0; i < 127; i++) {
		startMotor(leftMotor, i);
		wait(.25);
	}
	stopMotor(leftMotor);
	*/
}
