#pragma config(Sensor, dgtl2,  bmp,            sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
/*
 Wait for the bumper switch to be bumped
 Note that a bump occurs when a switch is pressed and released and not simply pressed and held
 Both motors turn on at half power until the sensor is bumped again
 Both motors should then move in reverse at half power for 3.5 seconds
 Both motors will stop.
 */

 waitUntil(SensorValue[dgtl2] == 1);
 waitUntil(SensorValue[dgtl2] == 0);

 startMotor(leftMotor, 63.5);
 startMotor(rightMotor, 63.5);

 waitUntil(SensorValue[dgtl2] == 1);
 waitUntil(SensorValue[dgtl2] == 0);

 startMotor(leftMotor, -63.5);
 startMotor(rightMotor, -63.5);

 wait(3.5);

 stopMotor(leftMotor);
 stopMotor(rightMotor);
}
