#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Test
  Team Members: Owen Scott, Peter McKibben
  Date: 11/11/19
  Section: 1


  Task Description:



  Pseudocode:

*/

#define MAX_POWER = 127;
#define MIN_POWER = -127;
#define ZERO_POWER = 0;

struct State {
	int leftMotorPort, rightMotorPort, leftMotorPower, rightMotorPower;
}

struct State state;

void initState(State &stateVar) {
	struct State state;
	state.leftMotorPort = 2;
	state.rightMotorPort = 3;
	state.leftMotorPower = 0;
	state.rightMotorPower = 0;
	stateVar = state;
}

task main()
{                                     //Program begins, insert code within curly braces
	initState(state);

}

void operation20() {
	/*
	Write a program that performs the following simple behaviors
	Use the natural language functions where appropriate as shown below
	Add comments at the end of each command line to explain the purpose of each step
		Turn the rightMotor on forward at half speed for 5 seconds, and then stop
		Turn the leftMotor on in reverse at three-fourths speed for 2.5 seconds, and then stop
		Turn both motors on at full power while spinning in the same direction for 7.25 seconds, and then stop
	*/
	state.rightMotorPower = MAX_POWER * .5;
	updateExternalState();
	wait(5);
	state.rightMotorPower = ZERO_POWER;
	state.leftMotorPower = MIN_POWER * .75;
	updateExternalState();
	wait(2.5);
	state.leftMotorPower = MAX_POWER;
	state.rightMotorPower = MAX_POWER;
	updateExternalState();
	wait(7.25);
	initState(state);
	updateExternalState();
}

void updateExternalState() {
	startMotor(state.leftMotorPort, state.leftMotorPower);
	startMotor(state.rightMotorPort, state.rightMotorPower);
}
