#pragma config(StandardModel, "POE + CIM Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int most = 4096;
task main()
{
while (1 == 1) {
	if (SensorValue[in2] < most) {
		most = SensorValue[in2];
	}
}

}
