#pragma config(StandardModel, "POE + CIM Testbed")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (1 == 1) {
		if (SensorValue[dgtl2] == 1) {
			startMotor(port2, 127);
		} else {
			stopMotor(port2);
		}
	}
}
