#pragma config(Sensor, dgtl1,  firstFloorButton, sensorTouch)
#pragma config(Sensor, dgtl2,  secondFloorButton, sensorTouch)
#pragma config(Sensor, dgtl3,  thirdFloorButton, sensorTouch)
#pragma config(Sensor, dgtl4,  firstFloorLED,  sensorDigitalOut)
#pragma config(Sensor, dgtl5,  secondFloorLED, sensorDigitalOut)
#pragma config(Sensor, dgtl6,  thirdFloorLED,  sensorDigitalOut)
#pragma config(Sensor, dgtl7,  sonar,          sensorSONAR_mm)
#pragma config(Motor,  port1,           elevatorMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static const byte MOTOR_DIRECTION = 1; // TODO: Update this

static const byte OPPOSITE = -1;
static const byte TOLERANCE = 10; // mm

static const byte INACTIVITY_TIMEOUT = 30;

static const float MM_PER_INCH = 25.4;
static const float FIRST_FLOOR_SONAR_READING = 1.5 * MM_PER_INCH;
static const float SECOND_FLOOR_SONAR_READING = 10 * MM_PER_INCH; // TODO: Update this
static const float THIRD_FLOOR_SONAR_READING = 20 * MM_PER_INCH; // TODO: Update this

// Waits for 30 seconds of inactivity before ending the program
task timeout() {
	wait(INACTIVITY_TIMEOUT);
	stopAllTasks();
}

task main() {
	while (1 == 1) {
		if (SensorValue[dgtl1] == 1) {

		} else if (SensorValue[dgtl2] == 1) {

		} else if (SensorValue[dgtl3] == 1) {

		}
	}
}

void targetLevel(float targetLevel) {
	while (SensorValue[sonar] - targetLevel > TOLERANCE * OPPOSITE && SensorValue[sonar] - targetLevel < TOLERANCE) {
		if (SensorValue[sonar] < targetLevel) {

		}
	}
	stopMotor(elevatorMotor);
}
